replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  pullPolicy: IfNotPresent
  tag: "7.17.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000      # Run as user with UID 1000
  fsGroup: 1000        # Set group ownership to GID 1000

securityContext:
  runAsUser: 1000      # Run the container as UID 1000
  runAsGroup: 1000     # Run the container as GID 1000
  fsGroup: 1000        # Set group ownership to GID 1000

service:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300

ingress:
  enabled: false
  hosts:
    # - host: "your-domain.com"
    - paths:
        - path: /api/v1
          pathType: Prefix
  tls: []

resources: {}

env:
  - name: discovery.type
    value: "single-node"

livenessProbe:
  httpGet:
    path: /
    port: 9200  # Ensure this matches your service port
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: 9200  # Ensure this matches your service port
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

extraVolumes: []
  # Example for mounting an emptyDir volume
  # - name: my-volume
  #   emptyDir: {}

extraVolumeMounts: []
  # Example for mounting a volume into the container
  # - name: elasticsearch-data
  #   mountPath: /usr/share/elasticsearch/data

# Init container to install plugins before starting Elasticsearch
initContainers:
  - name: install-plugins
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    command: ["/bin/sh", "-c"]
    args:
      - |
        ./bin/elasticsearch-plugin install analysis-nori --batch
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
      - name: elasticsearch-data
        mountPath: /usr/share/elasticsearch/data