replicaCount: 1

image:
  repository: dreamthre/waguwagu-elastic-server
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []

resources: {}


# env:
#   - name: "SPRING_APPLICATION_NAME"
#     value: "elastic-application"
#   - name: "SPRING_ELASTICSEARCH_REST_URIS"
#     value: "http://localhost:9200"


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 200
  targetCPUUtilizationPercentage: 100

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}