replicaCount: 1

image:
  repository: dreamthre/waguwagu-elastic-server
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000      # Ensuring the container runs with a non-root user
  fsGroup: 1000        # Set group ownership to GID 1000

securityContext:
  runAsUser: 1000      # Ensuring the container runs with a non-root user
  runAsGroup: 1000     # Run the container as GID 1000
  fsGroup: 1000        # Set group ownership to GID 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1"
# env:
#   - name: "SPRING_APPLICATION_NAME"
#     value: "elastic-application"
#   - name: "SPRING_ELASTICSEARCH_REST_URIS"
#     value: "http://elastic:9200"  # Ensure this points to the correct Elasticsearch service URL
#   - name: "SPRING_PROFILES_ACTIVE"
#     value: "production"  # Set the active profile to 'production', adjust as necessary

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 200
  targetCPUUtilizationPercentage: 100

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
